### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EnderCraft202** [kicjow/Crazy-Auctions#4]
[18:22:03 INFO]: EnderCraft202 issued server command: /ah

> [18:22:03 ERROR]: nullorg.bukkit.command.CommandException: Unhandled exception executing command 'ah' in plugin CrazyAuctions v1.0.1    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]  at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]  at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]   at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]Caused by: java.lang.NullPointerException at me.badbones69.crazyauctions.Api.makeItem(Api.java:63) ~[?:?] at me.badbones69.crazyauctions.GUI.openShop(GUI.java:109) ~[?:?]    at me.badbones69.crazyauctions.Main.onCommand(Main.java:70) ~[?:?]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"] ... 15 more>

**Comment by kicjow** [comment]
Please pastebin your Config.yml and paste the link here.

**Comment by EnderCraft202** [comment]
http://pastebin.com/YAK4YPNj

**Comment by kicjow** [comment]
I said PasteBin your Config.yml
