### ISSUE TITLE
Not recieving items when removing them off the ah

### ISSUE THREAD

**Issue by BladeGuy22** [kicjow/Crazy-Auctions#6]
My players are having the issue that when they remove a item off of the auction house they do not receive the item, i have looked through the config and cant seem to see anywhere where it says that i may need to enable it or something. I may just be being blind. Thanks

also these players do not have op nor all permissions so i may of missed a permission or something but again, i cant seem to see anything where it says about a permission with something like that. They can list things and buy things fine on the ah but not get them back, not sure if that is intentional or a bug.

Thanks, Ollie.

**Comment by BluueJay** [comment]
Hey,

Check if your players have the "crazyauctions.access" permission. If they do, their items should be sent to /ah expired (or /ca expired) rather than straight to their inventory.
