### ISSUE TITLE
Bad timings

### ISSUE THREAD

**Issue by xion87** [kicjow/Crazy-Auctions#7]
Sometimes my server tps go down and i see crazyauctions is the first here....
https://timings.spigotmc.org/?url=mawuqemiyo

**Comment by xion87** [comment]
I examined and crash logs and seem the issue is the update thing that is doing things on main thread, also caused some crashes to my server

**Comment by kicjow** [comment]
Yes, I am sorry about that. Most of my plugins have this fixed and I'll make sure to fix it on CA asap.

**Comment by kicjow** [comment]
Has been fixed and will be in the next update.
